name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # 원하는 Node.js 버전

      - name: Install dependencies
        run:
          cd db && npm install  # 필요에 따라 변경

      - name: run
        run:
          node db/index.js

      - name: Deploy
        run: |
          az webapp up --name db-app --rg-hohwancivil-team  --location koreacentral

