name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # 배포할 브랜치 이름

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # 원하는 Node.js 버전

      - name: Install dependencies
        run: cd db && npm install

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'plzwork'  # Azure App Service 이름
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Set environment variables
        run: |
          az webapp config appsettings set --name plzwork --resource-group rg-hohwancivil-team --settings DB_ENDPOINT=${{ secrets.API_ENDPOINT }} DB_KEY=${{ secrets.API_KEY }}

      - name: Start application
        run: cd db && npm start